modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/Shoxie12/MCDJ/issues"
license="Apache License"
[[mods]]
modId="mcdj"
version="1.3"
displayName="MCDJ"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mcdj"
credits="This mod is uses a VorbisJava library by gagravarr"
authors="Shoxie"
description='''
This mod allow you to add an unlimited amount of your music as records in game.
All you need to do is just put your .ogg files to .minecraft/Music/ folder and restart Minecraft

And that's all!
'''