modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/Shoxie12/MCDJ/issues"
license="Apache License"
[[mods]]
modId="mcdj"
version="2.0"
displayName="MCDJ"
logoFile="mcdj.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mcdj"
credits="This mod is uses a VorbisJava library by gagravarr"
authors="Shoxie"
description='''
Allows you to add an unlimited amount of your music as music discs!
'''