modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Shoxie12/MCDJ/issues"
license="Apache License"
[[mods]]
modId="mcdj"
version="3.0.0"
displayName="MCDJ"
logoFile="mcdj.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mcdj"
credits=""
authors="Shoxie"
description='''
Allows you to add an unlimited amount of music disc in just a few clicks!

MCDJ uses FFmpeg to work with mp3
MCDJ is uses a VorbisJava library by gagravarr
'''